#!/usr/bin/env python3
"""
Fallback UV generator for simple meshes like a cube.
Reads out_cube.obj (with broken UVs) and writes out_cube_fixed.obj
with simple projection-based per-vertex UVs.
"""

import sys
from pathlib import Path

in_path = Path("starter_code/part2_python/out_cube.obj")
out_path = Path("starter_code/part2_python/out_cube_fixed.obj")

if not in_path.exists():
    print("ERROR: Input OBJ not found:", in_path)
    sys.exit(1)

verts = []
faces = []

# Read vertices and triangular faces
with in_path.open() as f:
    for line in f:
        line = line.strip()
        if line.startswith("v "):
            parts = line.split()
            x = float(parts[1])
            y = float(parts[2])
            z = float(parts[3])
            verts.append((x, y, z))
        elif line.startswith("f "):
            parts = line.split()[1:]
            tri = []
            for p in parts:
                # handle "v/vt" and "v"
                if "/" in p:
                    v_idx = int(p.split("/")[0])
                else:
                    v_idx = int(p)
                tri.append(v_idx - 1)
            if len(tri) == 3:
                faces.append(tuple(tri))

if not verts or not faces:
    print("ERROR: No vertices/faces found in OBJ.")
    sys.exit(1)

# Generate per-vertex UVs by projecting x,z to [0,1]
xs = [v[0] for v in verts]
zs = [v[2] for v in verts]

xmin, xmax = min(xs), max(xs)
zmin, zmax = min(zs), max(zs)

dx = xmax - xmin if xmax != xmin else 1.0
dz = zmax - zmin if zmax != zmin else 1.0

uvs = []
for (x, y, z) in verts:
    u = (x - xmin) / dx
    v = (z - zmin) / dz
    # clamp
    u = max(0.0, min(1.0, u))
    v = max(0.0, min(1.0, v))
    uvs.append((u, v))

# Write new OBJ with v, vt, and f v/vt
with out_path.open("w") as f:
    f.write("# fixed UVs generated by fix_cube_uvs.py\n")
    for (x, y, z) in verts:
        f.write(f"v {x:.6f} {y:.6f} {z:.6f}\n")
    for (u, v) in uvs:
        f.write(f"vt {u:.6f} {v:.6f}\n")
    for (i0, i1, i2) in faces:
        f.write(f"f {i0+1}/{i0+1} {i1+1}/{i1+1} {i2+1}/{i2+1}\n")

print("Wrote fixed OBJ:", out_path)

